# Generated by Django 3.2.20 on 2023-07-10 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [#의존성(상속받는부분)
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.datetime(2023, 7, 10, 14, 18, 55, 707824, tzinfo=utc))),
                ('body', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('대기', '위험'), ('취소', '추행'), ('완료', '폭행'), ('침입', '침입')], max_length=20)),
            ],
        ),
    ]
