# Generated by Django 3.2.20 on 2023-07-11 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 11, 18, 20, 21, 436086, tzinfo=utc)),
        ),
    ]
