# Generated by Django 3.2.20 on 2023-07-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='resiNumEnd',
            new_name='residenceNumberEnd',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='resiNumStart',
            new_name='residenceNumberStart',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='blood',
            field=models.CharField(choices=[('미기재', '미기재'), ('A (RH+)', 'A (RH+)'), ('B (RH+)', 'B (RH+)'), ('O (RH+)', 'O (RH+)'), ('AB (RH+)', 'AB (RH+)'), ('A (RH-)', 'A (RH-)'), ('B (RH-)', 'B (RH-)'), ('O (RH-)', 'O (RH-)'), ('AB (RH-)', 'AB (RH-)')], default='미기재', max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='hair',
            field=models.CharField(choices=[('미기재', '미기재'), ('삭발', '삭발'), ('대머리', '대머리'), ('긴머리', '긴머리'), ('곱슬긴머리', '곱슬긴머리'), ('단발머리', '단발머리'), ('커트머리', '커트머리'), ('곱슬단발머리', '곱슬단발머리'), ('가발', '가발'), ('스포츠형', '스포츠형'), ('짧은머리(생머리)', '짧은머리(생머리)'), ('긴머리(생머리)', '긴머리(생머리)'), ('짧은머리(펌)', '짧은머리(펌)'), ('긴머리(펌)', '긴머리(펌)'), ('묶음머리', '묶음머리'), ('상고머리', '상고머리'), ('염색/탈색', '염색/탈색'), ('바가지머리', '바가지머리'), ('기타', '기타')], default='미기재', max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='scar',
            field=models.CharField(choices=[('미기재', '미기재'), ('머리', '머리'), ('얼굴', '얼굴'), ('팔', '팔'), ('손', '손'), ('등', '등'), ('몸통', '몸통'), ('둔부', '둔부'), ('다리', '다리'), ('발', '발'), ('기타', '기타')], default='미기재', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='tooth',
            field=models.CharField(choices=[('정상', '정상'), ('틀니', '틀니'), ('뻐드렁니', '뻐드렁니'), ('옹니', '옹니'), ('금니', '금니'), ('은니', '은니'), ('의치', '의치'), ('때운이빨', '때운이빨'), ('임플란트', '임플란트'), ('기타', '기타')], default='정상', max_length=100),
        ),
    ]
