# Generated by Django 3.2.20 on 2023-07-11 16:35

from django.db import migrations, models
import userinfo.models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_auto_20230711_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='blood',
            field=models.CharField(choices=[(userinfo.models.BloodChoice['UNDEFINED'], '미기재'), (userinfo.models.BloodChoice['A_POSITIVE'], 'A (RH+)'), (userinfo.models.BloodChoice['B_POSITIVE'], 'B (RH+)'), (userinfo.models.BloodChoice['O_POSITIVE'], 'O (RH+)'), (userinfo.models.BloodChoice['AB_POSITIVE'], 'AB (RH+)'), (userinfo.models.BloodChoice['A_NEGATIVE'], 'A (RH-)'), (userinfo.models.BloodChoice['B_NEGATIVE'], 'B (RH-)'), (userinfo.models.BloodChoice['O_NEGATIVE'], 'O (RH-)'), (userinfo.models.BloodChoice['AB_NEGATIVE'], 'AB (RH-)')], default='미기재', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='hair',
            field=models.CharField(choices=[(userinfo.models.HairChoice['UNDEFINED'], '미기재'), (userinfo.models.HairChoice['SHAVED'], '삭발'), (userinfo.models.HairChoice['BALD'], '대머리'), (userinfo.models.HairChoice['LONG_HAIR'], '긴머리'), (userinfo.models.HairChoice['CURLY_LONG_HAIR'], '곱슬긴머리'), (userinfo.models.HairChoice['SHORT_HAIR'], '단발머리'), (userinfo.models.HairChoice['CUT_HAIR'], '커트머리'), (userinfo.models.HairChoice['CURLY_SHORT_HAIR'], '곱슬단발머리'), (userinfo.models.HairChoice['WIG'], '가발'), (userinfo.models.HairChoice['SPORTY'], '스포츠형'), (userinfo.models.HairChoice['SHORT_NATURAL_HAIR'], '짧은머리(생머리)'), (userinfo.models.HairChoice['LONG_NATURAL_HAIR'], '긴머리(생머리)'), (userinfo.models.HairChoice['SHORT_PERMED_HAIR'], '짧은머리(펌)'), (userinfo.models.HairChoice['LONG_PERMED_HAIR'], '긴머리(펌)'), (userinfo.models.HairChoice['TIED_HAIR'], '묶음머리'), (userinfo.models.HairChoice['TOPKNOT'], '상고머리'), (userinfo.models.HairChoice['DYED_BLEACHED'], '염색/탈색'), (userinfo.models.HairChoice['BOWL_CUT'], '바가지머리'), (userinfo.models.HairChoice['OTHER'], '기타')], default='미기재', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='scar',
            field=models.CharField(choices=[(userinfo.models.ScarChoice['UNDEFINED'], '미기재'), (userinfo.models.ScarChoice['HEAD'], '머리'), (userinfo.models.ScarChoice['FACE'], '얼굴'), (userinfo.models.ScarChoice['ARM'], '팔'), (userinfo.models.ScarChoice['HAND'], '손'), (userinfo.models.ScarChoice['BACK'], '등'), (userinfo.models.ScarChoice['TORSO'], '몸통'), (userinfo.models.ScarChoice['BUTTOCK'], '둔부'), (userinfo.models.ScarChoice['LEG'], '다리'), (userinfo.models.ScarChoice['FOOT'], '발'), (userinfo.models.ScarChoice['OTHER'], '기타')], default='미기재', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='tooth',
            field=models.CharField(choices=[(userinfo.models.ToothChoice['NORMAL'], '정상'), (userinfo.models.ToothChoice['DENTURE'], '틀니'), (userinfo.models.ToothChoice['WISDOM_TOOTH'], '뻐드렁니'), (userinfo.models.ToothChoice['MOLAR'], '금니'), (userinfo.models.ToothChoice['SILVER_TOOTH'], '은니'), (userinfo.models.ToothChoice['DENTAL_BRIDGE'], '의치'), (userinfo.models.ToothChoice['TARTAR_TOOTH'], '때운이빨'), (userinfo.models.ToothChoice['IMPLANT'], '임플란트'), (userinfo.models.ToothChoice['OTHER'], '기타')], default='정상', max_length=100),
        ),
    ]
