# Generated by Django 3.2.20 on 2023-07-11 18:06

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_auto_20230712_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianInfo',
            fields=[
                ('user_guard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='userinfo.userinfo')),
                ('guard_name', models.CharField(max_length=10)),
                ('guard_residenceNumberStart', models.PositiveIntegerField()),
                ('guard_residenceNumberEnd', models.PositiveIntegerField()),
                ('guard_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
    ]
