# Generated by Django 3.2.20 on 2023-07-11 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0005_guardianinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardianinfo',
            name='guard_phone',
        ),
        migrations.AddField(
            model_name='guardianinfo',
            name='phoneNumber',
            field=models.CharField(max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
